name: Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Fairy-Stockfish
      run: |
        cpuid
        curl -Lo stockfish-x86_64 https://github.com/gbtami/Fairy-Stockfish/releases/latest/download/stockfish-x86_64
        chmod +x stockfish-x86_64

    - name: Fairyfishnet Tests
      run: |
        python3 test.py -v
